name: Mirror images to RHISV Quay Org

on:
  workflow_call:
    inputs:
      sourceImageName:
        required: true
        type: string
      sourceImageTag:
        required: true
        type: string
    secrets:
      sourceImageRegistry:
        required: true

env:
  DEST_IMAGE_NAME: preflight-test

jobs:
  mirror-images-to-rhisv:
    needs: []
    name: Mirror Images
    runs-on: ubuntu-latest
    steps:
    - name: Podman Login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ secrets.RHISV_IMAGE_REGISTRY }}
        username: ${{ secrets.RHISV_REGISTRY_USER }}
        password: ${{ secrets.RHISV_REGISTRY_PASSWORD }}

    - name: Copy Images from Source to Dest
      id: skopeo-copy-image
      run: |
        skopeo copy --all --preserve-digests ${{ secrets.sourceImageRegistry }}/${{ inputs.sourceImageName }}:${{ inputs.sourceImageTag }}-linux-amd64 ${{ secrets.RHISV_IMAGE_REGISTRY }}/${{ env.DEST_IMAGE_NAME }}:${{ inputs.sourceImageTag }}-linux-amd64
        skopeo copy --all --preserve-digests ${{ secrets.sourceImageRegistry }}/${{ inputs.sourceImageName }}:${{ inputs.sourceImageTag }}-linux-ppc64le ${{ secrets.RHISV_IMAGE_REGISTRY }}/${{ env.DEST_IMAGE_NAME }}:${{ inputs.sourceImageTag }}-linux-ppc64le
        skopeo copy --all --preserve-digests ${{ secrets.sourceImageRegistry }}/${{ inputs.sourceImageName }}:${{ inputs.sourceImageTag }}-linux-arm64 ${{ secrets.RHISV_IMAGE_REGISTRY }}/${{ env.DEST_IMAGE_NAME }}:${{ inputs.sourceImageTag }}-linux-arm64
        skopeo copy --all --preserve-digests ${{ secrets.sourceImageRegistry }}/${{ inputs.sourceImageName }}:${{ inputs.sourceImageTag }}-linux-s390x ${{ secrets.RHISV_IMAGE_REGISTRY }}/${{ env.DEST_IMAGE_NAME }}:${{ inputs.sourceImageTag }}-linux-s390x
        skopeo copy --all --preserve-digests ${{ secrets.sourceImageRegistry }}/${{ inputs.sourceImageName }}:${{ inputs.sourceImageTag }} ${{ secrets.RHISV_IMAGE_REGISTRY }}/${{ env.DEST_IMAGE_NAME }}:${{ inputs.sourceImageTag }}